import type { 
  Product, 
  Brand, 
  Category,
  Collection, 
  Announcement
} from "./types";

// Mock Brands
export const MOCK_BRANDS: Brand[] = [
  { id: "brand-burberry", name: "BURBERRY", slug: "burberry", country: "UK" },
  { id: "brand-coach", name: "COACH", slug: "coach", country: "USA" },
  { id: "brand-hermes", name: "HERMÈS", slug: "hermes", country: "France" },
  { id: "brand-balenciaga", name: "BALENCIAGA", slug: "balenciaga", country: "Spain" },
  { id: "brand-fendi", name: "FENDI", slug: "fendi", country: "Italy" },
  { id: "brand-gucci", name: "GUCCI", slug: "gucci", country: "Italy" },
  { id: "brand-chanel", name: "CHANEL", slug: "chanel", country: "France" },
  { id: "brand-lv", name: "LOUIS VUITTON", slug: "louis-vuitton", country: "France" },
  { id: "brand-prada", name: "PRADA", slug: "prada", country: "Italy" },
  { id: "brand-cartier", name: "CARTIER", slug: "cartier", country: "France" },
  { id: "brand-rolex", name: "ROLEX", slug: "rolex", country: "Switzerland" },
  { id: "brand-sl", name: "SAINT LAURENT", slug: "saint-laurent", country: "France" },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-bags", name: "Túi xách", slug: "bags" },
  { id: "cat-shoes", name: "Giày", slug: "shoes" },
  { id: "cat-watches", name: "Đồng hồ", slug: "watches" },
  { id: "cat-clothing", name: "Quần áo", slug: "clothing" },
  { id: "cat-accessories", name: "Phụ kiện", slug: "accessories" },
];

const getBrand = (slug: string) => MOCK_BRANDS.find(b => b.slug === slug);
const getCat = (slug: string) => MOCK_CATEGORIES.find(c => c.slug === slug);

// Mock Products
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-01",
    brand: getBrand("hermes"),
    name: "Birkin 30 Epsom Leather",
    slug: "birkin-30-epsom-leather",
    price: 18500,
    oldPrice: 22000,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuD4xVRWk-Ss25In68X36868scegRiJNN_5swPB_lnz9X5El_3-nyLQSMJFCFp_IZvblTxnc7XmW2gwvTCxN30UPTzrr9AzMgnHGyZzEKHfh-X2z4rBipl3EgoaUQyxXNArHvoeN5cAHZyPvTAbfv5yn4AwQEukI3Yj3_qGKBlWxojk4lVsqK7yiic_T4PSHOIZJ32ia-hZrELqQ4Ddfqcx7Lk_xfCzZQhmLc_wsXK36c_VRRcXyUek-Flw5-5WFc0dDE7P6eBeeydo"],
    tags: ["NEW"],
    category: getCat("bags"),
    sizes: ["30cm"],
    condition: "LIKE_NEW",
    conditionPercent: 98,
    authenticType: "AUTHENTIC",
    isNewArrival: true,
    isHotDeal: false,
    status: "AVAILABLE",
    description: "Túi xách Hermès Birkin 30 bằng da Epsom chính hãng. Đi kèm hộp, khóa, chìa khóa và túi chống bụi.",
    createdAt: new Date("2026-04-25"),
    views: 234,
    stock: 1,
    weight: 500,
    stockPerSize: { "30cm": 1 },
  },
  {
    id: "prod-02",
    brand: getBrand("rolex"),
    name: "Oyster Perpetual 41",
    slug: "oyster-perpetual-41",
    price: 9200,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDbe35NhvHqsoN6tRcTX40mC90x5ZvJQv5ER043P5ahyV_bdkku47-hEdOaM5Mwd4RWtln0NFJY8XHUSdG0taaJ8dskF3KGUhX95a7MO1qxKKaqkShEdilejqcUJDXXmerD6Yb2Ow3DF1EkX2_cWEJCl_OKo4vHijreVFykVPLl8GAfJVkddxyHcpEGHkXkz8qf2TpuJZbkfpJuSZjfullthZyeigFLRzfnERut_FBUqG-MVQ1n9TGV7VdfW5QeNfW6Zjua9vVHROg"],
    category: getCat("watches"),
    sizes: ["41mm"],
    condition: "EXCELLENT",
    conditionPercent: 92,
    authenticType: "AUTHENTIC",
    isHotDeal: true,
    isNewArrival: false,
    status: "SOLD_OUT",
    tags: ["HOT"],
    description: "Đồng hồ Rolex Oyster Perpetual 41mm. Đầy đủ hộp và giấy tờ.",
    createdAt: new Date("2026-04-20"),
    views: 456,
    stock: 0,
    weight: 500,
    stockPerSize: { "41mm": 0 },
  },
  {
    id: "prod-03",
    brand: getBrand("balenciaga"),
    name: "Giày Triple S Màu Kem",
    slug: "giay-triple-s-mau-kem",
    price: 1150,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDUoM8CANPDkqu9Nf9Vz_YMYHo5c0S7izgDWazT53FgeFrr7NrfLQV-sSBB6LZzGab3nCmtxBQ8AwYC7o8y6zLXgsq_PSJJUcYR_zeDtXbg1wi7RVq56HJJXflnqUAZNIPMgG1ugURO3JZJ793rXUH9DblYFsRbDukbQrotw2r22zNNtRIRkv53d8q-zy7VAT57z5I5vG8ObcpURKmhhMI4d3KOJC8Ngy4AnHgnpemqU622EiM0a0ptTFZbvNtBDGNSTmz8t0OMBE8"],
    tags: ["HIẾM"],
    category: getCat("shoes"),
    sizes: ["39", "40", "41", "42", "43"],
    condition: "EXCELLENT",
    conditionPercent: 85,
    authenticType: "AUTHENTIC",
    description: "Giày Balenciaga Triple S màu kem. Size EU 42.",
    isHotDeal: false,
    isNewArrival: false,
    status: "AVAILABLE",
    createdAt: new Date("2026-04-18"),
    views: 189,
    stock: 3,
    weight: 500,
    stockPerSize: { "39": 0, "40": 1, "41": 1, "42": 0, "43": 1 },
  },
  {
    id: "prod-04",
    brand: getBrand("burberry"),
    name: "Áo khoác Trench Kensington Heritage",
    slug: "ao-khoac-trench-kensington",
    price: 2450,
    oldPrice: 2800,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuBp1MLTjipzYLyjVKv4PdM1R-U2FONCgZ5EHHvuTUhSa0xJDJTV3DLMCt1j2KhGrqRl50TlwrKYAHFFaK7lAnqGaNEMb3J0spfuqWMUPkvEt-aB4SJSAfImTBRLhf0s8UiOHV6bTY07u9j_VlcWdu1Ik4Hj0bVfVhrDQRdWCnQYg6VyAVXpubnkneczCPoJd381qiWJdE28ihYWCtAwhHKLXdqh4zIjaW3UX3owVKXbhB5xOslm69LrIE0JpG7IWTu7m4ZsSvt79H4"],
    category: getCat("clothing"),
    sizes: ["S", "M", "L", "XL"],
    condition: "EXCELLENT",
    conditionPercent: 88,
    authenticType: "LIKE_AUTHENTIC",
    isHotDeal: true,
    isNewArrival: false,
    status: "AVAILABLE",
    tags: [],
    description: "Áo khoác trench Burberry Kensington Heritage màu mật ong.",
    sizingRong: "58cm",
    sizingDai: "108cm",
    sizingBung: "",
    sizingDayQuan: "",
    createdAt: new Date("2026-04-15"),
    views: 312,
    stock: 1,
    weight: 500,
    stockPerSize: { "S": 1, "M": 0, "L": 0, "XL": 0 },
  },
  {
    id: "prod-05",
    brand: getBrand("gucci"),
    name: "Marmont Matelassé Mini",
    slug: "marmont-matelasse-mini",
    price: 1890,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDtveEFZ_JexwPM_KCVFtdx0cZE_U7wUOWYwSvNOwh0va6Hmheys0ZKAe4fTt5UIZ-QvuOFMndBoZCS1S95_d4jc5aAq2dqA0Y2zdU4mwJSpvoM-xsKjdQd721PoD9SM6aczOPgX6so6ZDDPHslZKjBD7bwxPtKibDe6EP9vHubr-RbdNcTjoWcvJnEh3K3ftOVpDB3kTb-yRKjVw9ZPOnBbOMZihd7uLCu3MXkYJQjcfvzTzHjXtX9YnVoptj6NJDAkbD6_01u-mA"],
    category: getCat("bags"),
    sizes: ["Mini"],
    condition: "LIKE_NEW",
    conditionPercent: 99,
    authenticType: "AUTHENTIC",
    isNewArrival: true,
    isHotDeal: false,
    status: "AVAILABLE",
    tags: [],
    description: "Túi đeo chéo Gucci GG Marmont Matelassé Mini.",
    createdAt: new Date("2026-04-24"),
    views: 567,
    stock: 2,
    weight: 500,
    stockPerSize: { "Mini": 2 },
  },
  {
    id: "prod-06",
    brand: getBrand("cartier"),
    name: "Santos de Cartier",
    slug: "santos-de-cartier",
    price: 7650,
    oldPrice: 9000,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDXlowOtFSsV35Wc3xcNXEvboGGI4rbSfojO_3BFJFWsVu8QqHEF9KCSz3CuiP0EkvcBMaltlQsBPzXGmG1Jx7P0IVITsBGpboXTdck3XzqzzkVeUY2cx-cpOP61WHuH5NcKcvUYAAvsi-QaDnbzf6TJPy-Np2ZLywgqp9PMUmqOd0MloXh5xg6Qetf8V4Ay8HcQ5UbQX7hv1msMeiDnPzjcKA0F32BhSm5LmzkxdOujMb0ilTAQJrnAkVQWdyVN-vyrZIOCTKE6LM"],
    tags: ["GIẢM 15%"],
    category: getCat("watches"),
    sizes: ["35mm", "39mm"],
    condition: "EXCELLENT",
    conditionPercent: 90,
    authenticType: "AUTHENTIC",
    isHotDeal: true,
    isNewArrival: false,
    status: "AVAILABLE",
    description: "Đồng hồ Cartier Santos de Cartier bằng thép. Bộ đầy đủ.",
    createdAt: new Date("2026-04-10"),
    views: 421,
    stock: 1,
    weight: 500,
    stockPerSize: { "35mm": 0, "39mm": 1 },
  },
  {
    id: "prod-07",
    brand: getBrand("prada"),
    name: "Kính mát Symbole",
    slug: "kinh-mat-symbole",
    price: 450,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuD42KiaGx3931dM9k7nO13iKQqr7aaO-6rJs_GQkBrdWthHzzK8FKUXWffGLfnX-DFALh-iM8fNfKeZV83Z-SXaz8kYPfZCMCSBtRM7Dou5HUphD0AhU_QGmF53e0mc-a5vl_eTEzyTfX9quMLYGXZTy9hsuy_26YFNaWcxcUuKaslWRXMeDXBMYCVdZ3I1CdQ7VJtGuij3Nj_ubIuMbX03D6iyqfyd3AD8rmAkwBrhEFuwNq4U0aL7vXar6Xa57b0ihcoxXxEUA7s"],
    category: getCat("accessories"),
    sizes: ["One Size"],
    condition: "LIKE_NEW",
    conditionPercent: 97,
    authenticType: "AUTHENTIC",
    description: "Kính mát Prada Symbole có bảo vệ tia UV.",
    isHotDeal: false,
    isNewArrival: false,
    status: "AVAILABLE",
    tags: [],
    createdAt: new Date("2026-04-22"),
    views: 98,
    stock: 5,
    weight: 500,
    stockPerSize: { "One Size": 5 },
  },
  {
    id: "prod-08",
    brand: getBrand("saint-laurent"),
    name: "Giày cao gót Anja da bóng",
    slug: "giay-cao-got-anja",
    price: 795,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuDTw0qh3kxz9DQJ4t81Nss6jlG6fKjWDFcO1YZj-EH37o7yYGqw3adoVSOjwj9fXMFM25D5KAG8wPJWtOP2L8t74LQ56xRbHrQYLKNEMMbrWsa8ImmY-kOBCNp7loC-YSd1ZPRc96vLhubN6KIygvaAKR9NxMYZ1U5aDwnLy4h1gIQ_NKRBcM2eD1R7xgMTzgvS2CmLg8Q3KBFJMfEt4ZH8qRRVI3l5jhZXj40KwQ9nalhz-Od7XdhkOmfCI23zrxzyApDHQ7kVQOs"],
    category: getCat("shoes"),
    sizes: ["36", "37", "38", "39", "40"],
    condition: "EXCELLENT",
    conditionPercent: 87,
    authenticType: "AUTHENTIC",
    description: "Giày cao gót Saint Laurent Anja da bóng. Size EU 38.",
    isHotDeal: false,
    isNewArrival: false,
    status: "AVAILABLE",
    tags: [],
    createdAt: new Date("2026-04-19"),
    views: 167,
    stock: 4,
    weight: 500,
    stockPerSize: { "36": 1, "37": 0, "38": 2, "39": 0, "40": 1 },
  },
];

// Mock Collections
export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    name: "Hàng mới về",
    slug: "new-arrivals",
    description: "Những món đồ xa xỉ mới nhất vừa được thêm vào bộ sưu tập của chúng tôi.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    productCount: 42,
  },
  {
    id: "col-2",
    name: "Khuyến mãi nóng",
    slug: "hot-deals",
    description: "Ưu đãi có thời hạn cho các sản phẩm đã xác thực cao cấp.",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800",
    productCount: 16,
  },
  {
    id: "col-3",
    name: "Thường ngày",
    slug: "casual",
    description: "Đồ xa xỉ thường ngày cho tủ đồ hiện đại.",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800",
    productCount: 28,
  },
  {
    id: "col-4",
    name: "Streetwear",
    slug: "streetwear",
    description: "Sang trọng đô thị kết hợp phong cách đương đại.",
    image: "https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=800",
    productCount: 35,
  },
];

// Mock Announcements
export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  { id: "ann-1", text: "MỚI VỀ 42 MÓN TUẦN NÀY", icon: "★", isActive: true },
  { id: "ann-2", text: "ĐỔI TRẢ TRONG 7 NGÀY", icon: "★", isActive: true },
  { id: "ann-3", text: "AUTHENTIC GUARANTEED", icon: "★", isActive: true },
  { id: "ann-4", text: "MIỄN PHÍ GIAO HÀNG ĐƠN TỪ 500K", icon: "★", isActive: true },
];
